apiVersion: v1
kind: Service
metadata:
  name: csi-snapshot-webhook
  namespace: openshift-cluster-storage-operator
  labels:
    app: csi-snapshot-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: csi-snapshot-webhook-secret
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 443
  selector:
    app: csi-snapshot-webhook
