apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: snapshot.storage.k8s.io
  namespace: csi-snapshot-controller-operator
  labels:
    app: csi-snapshot-webhook
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
webhooks:
  - name: volumesnapshotclasses.snapshot.storage.k8s.io
    clientConfig:
      service:
        name: csi-snapshot-webhook
        namespace: openshift-cluster-storage-operator
        path: "/volumesnapshot"
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["snapshot.storage.k8s.io"]
        apiVersions: ["v1beta1"]
        resources: ["volumesnapshots", "volumesnapshotcontents"]
    sideEffects: None
    failurePolicy: Ignore
